ARM: shmobile: kzm9g-reference dts: Use tabs for indentation
Checkpatch says:

ERROR: code indent should use tabs where possible

Signed-off-by: Geert Uytterhoeven <geert+renesas@glider.be>
Signed-off-by: Simon Horman <horms+renesas@verge.net.au>
(cherry picked from commit 40c488df84f9fbf4b84b4baed6e2cec4a2d946ed)
Signed-off-by: Simon Horman <horms+renesas@verge.net.au>