ARM: shmobile: r8a7779 dtsi: Use tabs for indentation
Checkpatch says:

ERROR: code indent should use tabs where possible

Signed-off-by: Geert Uytterhoeven <geert+renesas@glider.be>
Signed-off-by: Simon Horman <horms+renesas@verge.net.au>
(cherry picked from commit 99e544c782ba03855b9b6762b73915565065dbf8)
Signed-off-by: Simon Horman <horms+renesas@verge.net.au>